/**:
  ros__parameters:
    ntrip:
      host: "3.143.243.81"
      user_name: "denemeMelih12@gmail.com"
      password: ""
      mount_point: "Droneqube002"
      port: 2101
      use_nav_sat_fix_init: true
      nav_sat_fix_topic_name: "/robins/raw/nav_sat_fix"
      init_ntrip_location_lat: 39.9178
      init_ntrip_location_lon: 32.7726

    serial_port:
      publish_port_rtcm: false
      name: "/dev/pts/3"
      baud_rate: 460800

    rtcm_publisher:
      publish_rtcm: true
      rtcm_topic: "/rtcm"
      rtcm_frame_id: "rtcm"